StockManagementSystem/Models/ErrorViewModel.cs
using System;

namespace StockManagementSystem.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StockManagementSystem/Controllers/BatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StockManagementSystem.Data;
using StockManagementSystem.Data.Models;
using StockManagementSystem.Data.ViewModels;

namespace StockManagementSystem.Controllers
{
    [Authorize]
    public class BatchesController : Controller
    {
        private readonly IDataManager dataManager;

        public BatchesController(IDataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        // GET: Batches
        public async Task<IActionResult> Index()
        {
            return View(dataManager.GetBatches());
        }

        // GET: Batches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            BatchViewModel batch = dataManager.GetBatch(id);
            
            if (batch == null)
            {
                return NotFound();
            }

            return View(batch);
        }

        // GET: Batches/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Batches/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BatchViewModel batch)
        {
            if (ModelState.IsValid)
            {
                await dataManager.NewBatch(batch);
                return RedirectToAction(nameof(Index));
            }
            return View(batch);
        }

        // GET: Batches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            BatchViewModel batch = dataManager.GetBatch(id);
            if (batch == null)
            {
                return NotFound();
            }
            return View(batch);
        }

        // POST: Batches/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BatchViewModel batch)
        {
            if(batch == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await dataManager.EditBatch(batch);
                return RedirectToAction(nameof(Index));
            }
            return View(batch);
        }

        // GET: Batches/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            BatchViewModel batch = dataManager.GetBatch(id);

            if (batch == null)
            {
                return NotFound();
            }

            return View(batch);
        }

        // POST: Batches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await dataManager.DeleteBatch(id);

            return RedirectToAction(nameof(Index));
        }


    }
}

StockManagementSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StockManagementSystem.Data;
using StockManagementSystem.Data.ViewModels;
using StockManagementSystem.Models;

namespace StockManagementSystem.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly IDataManager dataManager;

        public HomeController(IDataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Index()
        {
            HomeViewModel model = new HomeViewModel
            {
                stockViewModels = dataManager.GetStocks().OrderBy(s=>s.Fruit)
            };

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StockManagementSystem/Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StockManagementSystem.Data;

namespace StockManagementSystem.Controllers
{
    [Authorize]
    public class StocksController : Controller
    {
        private readonly IDataManager dataManager;

        public StocksController(IDataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.GetStocks());
        }
    }
}

StockManagementSystem/Views/Batches/Create.cshtml
@model StockManagementSystem.Data.ViewModels.BatchViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Batch</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Fruit" class="control-label"></label>
                <input asp-for="Fruit" class="form-control" />
                <span asp-validation-for="Fruit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Variety" class="control-label"></label>
                <input asp-for="Variety" class="form-control" />
                <span asp-validation-for="Variety" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StockManagementSystem/Views/Batches/Delete.cshtml
@model StockManagementSystem.Data.ViewModels.BatchViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Batch</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Fruit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fruit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Variety)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Variety)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

StockManagementSystem/Views/Batches/Details.cshtml
@model StockManagementSystem.Data.ViewModels.BatchViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Batch</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Fruit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fruit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Variety)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Variety)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

StockManagementSystem/Views/Batches/Edit.cshtml
@model StockManagementSystem.Data.ViewModels.BatchViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Batch</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Fruit" class="control-label"></label>
                <input asp-for="Fruit" class="form-control" />
                <span asp-validation-for="Fruit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Variety" class="control-label"></label>
                <input asp-for="Variety" class="form-control" />
                <span asp-validation-for="Variety" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StockManagementSystem/Views/Batches/Index.cshtml
@model IEnumerable<StockManagementSystem.Data.ViewModels.BatchViewModel>

@{
    ViewData["Title"] = "Batches";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Batches</h2>

<p>
    <a class="btn btn-success" asp-controller="Stocks" asp-action="Index">View Stocks</a>
    <a class="btn btn-success" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fruit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Variety)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fruit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Variety)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

StockManagementSystem/Views/Home/Index.cshtml
@model StockManagementSystem.Data.ViewModels.HomeViewModel

@{
    ViewData["Title"] = "Home Page";
}


<div class="row">
    <div class="text-center">
        <h1>
            Stock Management System
        </h1>
        <a class="btn btn-primary btn-lg" asp-controller="Batches" asp-action="Index">Batches</a>
        <canvas id="stocksChart"></canvas>
    </div>
</div>

@section Scripts{
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

    <script>
        var ctx = document.getElementById('stocksChart').getContext('2d');
        var chart = new Chart(ctx, {
            // The type of chart we want to create
            type: 'bar',

            // The data for our dataset
            data: {
                labels: @Html.Raw(Json.Serialize(Model.stockViewModels.Select(m=> $"{m.Fruit} + {m.Variety}"))),
                datasets: [
                    {
                        label: 'Quantity',
                        backgroundColor: 'rgb(255, 99, 132)',
                        borderColor: 'rgb(255, 99, 132)',
                        data: @Html.Raw(Json.Serialize(Model.stockViewModels.Select(m => m.Quantity)))
                    },
                ]
            },

            // Configuration options go here
            options: {}
        });
    </script>
}

StockManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockManagementSystem</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">StockManagementSystem</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Batches" asp-action="Index">Batches</a></li>
                    <li><a asp-controller="Stocks" asp-action="Index">Stocks</a></li>
                    <li><a href="http://samsongabriels.co.uk">Portfolio Website</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - StockManagementSystem</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

StockManagementSystem/Views/Stocks/Index.cshtml
@model IEnumerable<StockManagementSystem.Data.ViewModels.StockViewModel>

@{
    ViewData["Title"] = "Stocks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Stocks</h2>

<p>
    <a class="btn btn-success" asp-controller="Batches" asp-action="Index">View Batches</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fruit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Variety)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fruit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Variety)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>

                </td>
            </tr>
        }
    </tbody>
</table>